// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "window.h"

UserInterface::UserInterface() {
  { w = new Fl_Double_Window(520, 530, "Gerador de aplica\303\247\303\265""es");
    w->user_data((void*)(this));
    { inputTitle = new Fl_Input(80, 34, 360, 24, "Title");
    } // Fl_Input* inputTitle
    { inputLabel = new Fl_Input(80, 58, 360, 24, "Label");
    } // Fl_Input* inputLabel
    { botao_clear = new Fl_Button(25, 115, 100, 25, "Clear");
    } // Fl_Button* botao_clear
    { botao_update = new Fl_Button(147, 115, 100, 25, "Update");
    } // Fl_Button* botao_update
    { botao_delete = new Fl_Button(270, 115, 100, 25, "Delete");
    } // Fl_Button* botao_delete
    { botao_insert = new Fl_Button(394, 115, 100, 25, "Insert");
    } // Fl_Button* botao_insert
    { Title_box = new Fl_Box(132, 12, 255, 16, "Gerador de aplica\303\247\303\265""es");
      Title_box->labelfont(1);
      Title_box->labelsize(22);
    } // Fl_Box* Title_box
    { browser = new Fl_Browser(25, 238, 470, 277);
      browser->type(2);
    } // Fl_Browser* browser
    { inputId = new Fl_Input(81, 83, 360, 24, "Id");
    } // Fl_Input* inputId
    { botao_export = new Fl_Button(150, 175, 100, 25, "Export");
    } // Fl_Button* botao_export
    { botao_generate = new Fl_Button(270, 175, 100, 25, "Generate");
    } // Fl_Button* botao_generate
    { botao_import = new Fl_Button(25, 175, 100, 25, "Import");
    } // Fl_Button* botao_import
    { inputFile = new Fl_Input(81, 145, 360, 24, "File name");
    } // Fl_Input* inputFile
    { botao_seta_titulo = new Fl_Button(395, 175, 100, 25, "Set Title");
    } // Fl_Button* botao_seta_titulo
    { caixa_titulo = new Fl_Box(115, 209, 300, 20);
    } // Fl_Box* caixa_titulo
    w->end();
  } // Fl_Double_Window* w
}
