// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef window_h
#define window_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Input.H>

class UserInterface {
public:
  UserInterface();
  Fl_Double_Window *tela;
  Fl_Box *imagem;
  Fl_Button *reset;
  Fl_Input *participantes;
  Fl_Box *numero_sorteado;
  Fl_Button *button_sort;
  Fl_Box *saida_ganhador;
};
#endif
